language: node_js
node_js:
    - 0.8

branches:
    only:
        - master

before_script:
    - npm install -g grunt-cli

env:
    global:
        - secure: "JgUp4gbrOTMU5s6EQA/iAl356YlAlwxHqmlkoQWDA8bTRu8r7yNmRyGCMvmF\nMuiXP12OKYhyz4G9KscccJWafQh8ahPS6aQgfX6zOm5p2etFv5xEfx3rujh4\nrsPCdMB9mja60ybsL+0xmKaMu1RCYNUXl9iY5Zddar/C3oIDQFI=" 
